### ISSUE TITLE
Update colourscheme

### ISSUE THREAD

**Issue by jhaasdijk** [akramkazmi71/hacktoberfest-xrepos#29]
This issue serves as a place for discussion about the change in colourscheme. The changes can be viewed by comparing the following two screenshots:

`Current:`
https://i.imgur.com/ScCqEGA.png

`Proposed:`
https://i.imgur.com/INPCoKR.png

If you want to experiment with the updated branch, take a look at #28 

Thoughts?

**Comment by arshadkazmi42** [comment]
Thank you @jhaasdijk for creating this issue.
Let's discuss this, if everyone likes the proposed design we will get the PR merged

**Comment by jhaasdijk** [comment]
[![](https://api.gh-polls.com/poll/01DPXM7TEGKENESEYE9TTR04HN/Current%20colourscheme)](https://api.gh-polls.com/poll/01DPXM7TEGKENESEYE9TTR04HN/Current%20colourscheme/vote)
[![](https://api.gh-polls.com/poll/01DPXM7TEGKENESEYE9TTR04HN/Proposed%20colourscheme)](https://api.gh-polls.com/poll/01DPXM7TEGKENESEYE9TTR04HN/Proposed%20colourscheme/vote)
